spring:
  data:
    neo4j:
      uri: bolt://127.0.0.1:7687
      username: neo4j
      password:
  application:
    name: check-in-server
  profiles:
    active: default
  cloud:
    config:
      enabled:true
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-server-u-r-l-context: http://localhost:8761/eureka
server:
  port: 8082